openapi: 3.1.1
info:
  title: Model API
  version: 1.0.0
servers:
  - url: https://{endpoint}
paths:
  /v1/iotstage/auth/tokens:
    post:
      summary: 获取认证 Token
      operationId: generateToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CreateTokenReqDTO"
      responses:
        "200":
          description: 成功返回 Token
          headers:
            X-Subject-Token:
              schema:
                type: string
              description: 返回的用户 token，用于后续调用 API 时放入 X-Auth-Token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenRsp"
components:
  schemas:
    CreateTokenReqDTO:
      type: object
      required:
        - client_id
        - secret_id
      properties:
        client_id:
          type: string
          description: 用户名
        secret_id:
          type: string
          description: 密码
        project:
          $ref: "#/components/schemas/Project"
    Project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    TokenRsp:
      type: object
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
