/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CatalogNode;
import org.openapitools.client.model.ThingNode;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * AddViewNodesReq
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-26T20:31:18.115216+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class AddViewNodesReq {
  public static final String SERIALIZED_NAME_PARENT_ID = "parent_id";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  @jakarta.annotation.Nullable
  private String parentId;

  public static final String SERIALIZED_NAME_CATALOG_NODE = "catalog_node";
  @SerializedName(SERIALIZED_NAME_CATALOG_NODE)
  @jakarta.annotation.Nullable
  private CatalogNode catalogNode;

  public static final String SERIALIZED_NAME_THING_NODES = "thing_nodes";
  @SerializedName(SERIALIZED_NAME_THING_NODES)
  @jakarta.annotation.Nullable
  private List<ThingNode> thingNodes = new ArrayList<>();

  public AddViewNodesReq() {
  }

  public AddViewNodesReq parentId(@jakarta.annotation.Nullable String parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @jakarta.annotation.Nullable
  public String getParentId() {
    return parentId;
  }

  public void setParentId(@jakarta.annotation.Nullable String parentId) {
    this.parentId = parentId;
  }


  public AddViewNodesReq catalogNode(@jakarta.annotation.Nullable CatalogNode catalogNode) {
    this.catalogNode = catalogNode;
    return this;
  }

  /**
   * Get catalogNode
   * @return catalogNode
   */
  @jakarta.annotation.Nullable
  public CatalogNode getCatalogNode() {
    return catalogNode;
  }

  public void setCatalogNode(@jakarta.annotation.Nullable CatalogNode catalogNode) {
    this.catalogNode = catalogNode;
  }


  public AddViewNodesReq thingNodes(@jakarta.annotation.Nullable List<ThingNode> thingNodes) {
    this.thingNodes = thingNodes;
    return this;
  }

  public AddViewNodesReq addThingNodesItem(ThingNode thingNodesItem) {
    if (this.thingNodes == null) {
      this.thingNodes = new ArrayList<>();
    }
    this.thingNodes.add(thingNodesItem);
    return this;
  }

  /**
   * Get thingNodes
   * @return thingNodes
   */
  @jakarta.annotation.Nullable
  public List<ThingNode> getThingNodes() {
    return thingNodes;
  }

  public void setThingNodes(@jakarta.annotation.Nullable List<ThingNode> thingNodes) {
    this.thingNodes = thingNodes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddViewNodesReq addViewNodesReq = (AddViewNodesReq) o;
    return Objects.equals(this.parentId, addViewNodesReq.parentId) &&
        Objects.equals(this.catalogNode, addViewNodesReq.catalogNode) &&
        Objects.equals(this.thingNodes, addViewNodesReq.thingNodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parentId, catalogNode, thingNodes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddViewNodesReq {\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    catalogNode: ").append(toIndentedString(catalogNode)).append("\n");
    sb.append("    thingNodes: ").append(toIndentedString(thingNodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("parent_id");
    openapiFields.add("catalog_node");
    openapiFields.add("thing_nodes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AddViewNodesReq
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AddViewNodesReq.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AddViewNodesReq is not found in the empty JSON string", AddViewNodesReq.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AddViewNodesReq.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AddViewNodesReq` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("parent_id") != null && !jsonObj.get("parent_id").isJsonNull()) && !jsonObj.get("parent_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `parent_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parent_id").toString()));
      }
      // validate the optional field `catalog_node`
      if (jsonObj.get("catalog_node") != null && !jsonObj.get("catalog_node").isJsonNull()) {
        CatalogNode.validateJsonElement(jsonObj.get("catalog_node"));
      }
      if (jsonObj.get("thing_nodes") != null && !jsonObj.get("thing_nodes").isJsonNull()) {
        JsonArray jsonArraythingNodes = jsonObj.getAsJsonArray("thing_nodes");
        if (jsonArraythingNodes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("thing_nodes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `thing_nodes` to be an array in the JSON string but got `%s`", jsonObj.get("thing_nodes").toString()));
          }

          // validate the optional field `thing_nodes` (array)
          for (int i = 0; i < jsonArraythingNodes.size(); i++) {
            ThingNode.validateJsonElement(jsonArraythingNodes.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AddViewNodesReq.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AddViewNodesReq' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AddViewNodesReq> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AddViewNodesReq.class));

       return (TypeAdapter<T>) new TypeAdapter<AddViewNodesReq>() {
           @Override
           public void write(JsonWriter out, AddViewNodesReq value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AddViewNodesReq read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AddViewNodesReq given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AddViewNodesReq
   * @throws IOException if the JSON string is invalid with respect to AddViewNodesReq
   */
  public static AddViewNodesReq fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AddViewNodesReq.class);
  }

  /**
   * Convert an instance of AddViewNodesReq to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

