/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.ListSnapshotResp;
import org.openapitools.client.model.PropertyValueTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BatchListThingSnapshotsRespThingsInner
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-28T16:46:47.218966+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class BatchListThingSnapshotsRespThingsInner {
  public static final String SERIALIZED_NAME_THING_ID = "thing_id";
  @SerializedName(SERIALIZED_NAME_THING_ID)
  @jakarta.annotation.Nullable
  private String thingId;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  @jakarta.annotation.Nullable
  private Map<String, PropertyValueTime> properties = new HashMap<>();

  public static final String SERIALIZED_NAME_COMPONENTS = "components";
  @SerializedName(SERIALIZED_NAME_COMPONENTS)
  @jakarta.annotation.Nullable
  private Map<String, ListSnapshotResp> components = new HashMap<>();

  public BatchListThingSnapshotsRespThingsInner() {
  }

  public BatchListThingSnapshotsRespThingsInner thingId(@jakarta.annotation.Nullable String thingId) {
    this.thingId = thingId;
    return this;
  }

  /**
   * Get thingId
   * @return thingId
   */
  @jakarta.annotation.Nullable
  public String getThingId() {
    return thingId;
  }

  public void setThingId(@jakarta.annotation.Nullable String thingId) {
    this.thingId = thingId;
  }


  public BatchListThingSnapshotsRespThingsInner properties(@jakarta.annotation.Nullable Map<String, PropertyValueTime> properties) {
    this.properties = properties;
    return this;
  }

  public BatchListThingSnapshotsRespThingsInner putPropertiesItem(String key, PropertyValueTime propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

  /**
   * Get properties
   * @return properties
   */
  @jakarta.annotation.Nullable
  public Map<String, PropertyValueTime> getProperties() {
    return properties;
  }

  public void setProperties(@jakarta.annotation.Nullable Map<String, PropertyValueTime> properties) {
    this.properties = properties;
  }


  public BatchListThingSnapshotsRespThingsInner components(@jakarta.annotation.Nullable Map<String, ListSnapshotResp> components) {
    this.components = components;
    return this;
  }

  public BatchListThingSnapshotsRespThingsInner putComponentsItem(String key, ListSnapshotResp componentsItem) {
    if (this.components == null) {
      this.components = new HashMap<>();
    }
    this.components.put(key, componentsItem);
    return this;
  }

  /**
   * Get components
   * @return components
   */
  @jakarta.annotation.Nullable
  public Map<String, ListSnapshotResp> getComponents() {
    return components;
  }

  public void setComponents(@jakarta.annotation.Nullable Map<String, ListSnapshotResp> components) {
    this.components = components;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchListThingSnapshotsRespThingsInner batchListThingSnapshotsRespThingsInner = (BatchListThingSnapshotsRespThingsInner) o;
    return Objects.equals(this.thingId, batchListThingSnapshotsRespThingsInner.thingId) &&
        Objects.equals(this.properties, batchListThingSnapshotsRespThingsInner.properties) &&
        Objects.equals(this.components, batchListThingSnapshotsRespThingsInner.components);
  }

  @Override
  public int hashCode() {
    return Objects.hash(thingId, properties, components);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchListThingSnapshotsRespThingsInner {\n");
    sb.append("    thingId: ").append(toIndentedString(thingId)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("thing_id");
    openapiFields.add("properties");
    openapiFields.add("components");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BatchListThingSnapshotsRespThingsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchListThingSnapshotsRespThingsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BatchListThingSnapshotsRespThingsInner is not found in the empty JSON string", BatchListThingSnapshotsRespThingsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BatchListThingSnapshotsRespThingsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BatchListThingSnapshotsRespThingsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("thing_id") != null && !jsonObj.get("thing_id").isJsonNull()) && !jsonObj.get("thing_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `thing_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("thing_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchListThingSnapshotsRespThingsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchListThingSnapshotsRespThingsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchListThingSnapshotsRespThingsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchListThingSnapshotsRespThingsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchListThingSnapshotsRespThingsInner>() {
           @Override
           public void write(JsonWriter out, BatchListThingSnapshotsRespThingsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BatchListThingSnapshotsRespThingsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BatchListThingSnapshotsRespThingsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BatchListThingSnapshotsRespThingsInner
   * @throws IOException if the JSON string is invalid with respect to BatchListThingSnapshotsRespThingsInner
   */
  public static BatchListThingSnapshotsRespThingsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchListThingSnapshotsRespThingsInner.class);
  }

  /**
   * Convert an instance of BatchListThingSnapshotsRespThingsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

