/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BatchListThingSnapshotsRespThingsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BatchListThingSnapshotsResp
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-22T08:57:00.546871+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class BatchListThingSnapshotsResp {
  public static final String SERIALIZED_NAME_THINGS = "things";
  @SerializedName(SERIALIZED_NAME_THINGS)
  @javax.annotation.Nullable
  private List<BatchListThingSnapshotsRespThingsInner> things = new ArrayList<>();

  public BatchListThingSnapshotsResp() {
  }

  public BatchListThingSnapshotsResp things(@javax.annotation.Nullable List<BatchListThingSnapshotsRespThingsInner> things) {
    this.things = things;
    return this;
  }

  public BatchListThingSnapshotsResp addThingsItem(BatchListThingSnapshotsRespThingsInner thingsItem) {
    if (this.things == null) {
      this.things = new ArrayList<>();
    }
    this.things.add(thingsItem);
    return this;
  }

  /**
   * Get things
   * @return things
   */
  @javax.annotation.Nullable
  public List<BatchListThingSnapshotsRespThingsInner> getThings() {
    return things;
  }

  public void setThings(@javax.annotation.Nullable List<BatchListThingSnapshotsRespThingsInner> things) {
    this.things = things;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchListThingSnapshotsResp batchListThingSnapshotsResp = (BatchListThingSnapshotsResp) o;
    return Objects.equals(this.things, batchListThingSnapshotsResp.things);
  }

  @Override
  public int hashCode() {
    return Objects.hash(things);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchListThingSnapshotsResp {\n");
    sb.append("    things: ").append(toIndentedString(things)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("things");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BatchListThingSnapshotsResp
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchListThingSnapshotsResp.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BatchListThingSnapshotsResp is not found in the empty JSON string", BatchListThingSnapshotsResp.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BatchListThingSnapshotsResp.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BatchListThingSnapshotsResp` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("things") != null && !jsonObj.get("things").isJsonNull()) {
        JsonArray jsonArraythings = jsonObj.getAsJsonArray("things");
        if (jsonArraythings != null) {
          // ensure the json data is an array
          if (!jsonObj.get("things").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `things` to be an array in the JSON string but got `%s`", jsonObj.get("things").toString()));
          }

          // validate the optional field `things` (array)
          for (int i = 0; i < jsonArraythings.size(); i++) {
            BatchListThingSnapshotsRespThingsInner.validateJsonElement(jsonArraythings.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchListThingSnapshotsResp.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchListThingSnapshotsResp' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchListThingSnapshotsResp> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchListThingSnapshotsResp.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchListThingSnapshotsResp>() {
           @Override
           public void write(JsonWriter out, BatchListThingSnapshotsResp value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BatchListThingSnapshotsResp read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BatchListThingSnapshotsResp given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BatchListThingSnapshotsResp
   * @throws IOException if the JSON string is invalid with respect to BatchListThingSnapshotsResp
   */
  public static BatchListThingSnapshotsResp fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchListThingSnapshotsResp.class);
  }

  /**
   * Convert an instance of BatchListThingSnapshotsResp to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

