/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BriefAnalysisTask
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-27T18:38:37.514966+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class BriefAnalysisTask {
  public static final String SERIALIZED_NAME_TASK_ID = "task_id";
  @SerializedName(SERIALIZED_NAME_TASK_ID)
  @jakarta.annotation.Nullable
  private String taskId;

  public static final String SERIALIZED_NAME_TASK_NAME = "task_name";
  @SerializedName(SERIALIZED_NAME_TASK_NAME)
  @jakarta.annotation.Nullable
  private String taskName;

  public static final String SERIALIZED_NAME_CALC_TYPE = "calc_type";
  @SerializedName(SERIALIZED_NAME_CALC_TYPE)
  @jakarta.annotation.Nullable
  private String calcType;

  public static final String SERIALIZED_NAME_SCHEDULE_TYPE = "schedule_type";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_TYPE)
  @jakarta.annotation.Nullable
  private String scheduleType;

  public static final String SERIALIZED_NAME_PERIOD = "period";
  @SerializedName(SERIALIZED_NAME_PERIOD)
  @jakarta.annotation.Nullable
  private String period;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @jakarta.annotation.Nullable
  private Boolean enabled;

  public static final String SERIALIZED_NAME_EVENT_CLASS_ID = "event_class_id";
  @SerializedName(SERIALIZED_NAME_EVENT_CLASS_ID)
  @jakarta.annotation.Nullable
  private String eventClassId;

  public static final String SERIALIZED_NAME_EVENT_CLASS_NAME = "event_class_name";
  @SerializedName(SERIALIZED_NAME_EVENT_CLASS_NAME)
  @jakarta.annotation.Nullable
  private String eventClassName;

  public static final String SERIALIZED_NAME_MODEL_ID = "model_id";
  @SerializedName(SERIALIZED_NAME_MODEL_ID)
  @jakarta.annotation.Nullable
  private String modelId;

  public static final String SERIALIZED_NAME_MODEL_NAME = "model_name";
  @SerializedName(SERIALIZED_NAME_MODEL_NAME)
  @jakarta.annotation.Nullable
  private String modelName;

  public static final String SERIALIZED_NAME_CREATE_TIME = "create_time";
  @SerializedName(SERIALIZED_NAME_CREATE_TIME)
  @jakarta.annotation.Nullable
  private String createTime;

  public static final String SERIALIZED_NAME_UPDATE_TIME = "update_time";
  @SerializedName(SERIALIZED_NAME_UPDATE_TIME)
  @jakarta.annotation.Nullable
  private String updateTime;

  public BriefAnalysisTask() {
  }

  public BriefAnalysisTask taskId(@jakarta.annotation.Nullable String taskId) {
    this.taskId = taskId;
    return this;
  }

  /**
   * Get taskId
   * @return taskId
   */
  @jakarta.annotation.Nullable
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(@jakarta.annotation.Nullable String taskId) {
    this.taskId = taskId;
  }


  public BriefAnalysisTask taskName(@jakarta.annotation.Nullable String taskName) {
    this.taskName = taskName;
    return this;
  }

  /**
   * Get taskName
   * @return taskName
   */
  @jakarta.annotation.Nullable
  public String getTaskName() {
    return taskName;
  }

  public void setTaskName(@jakarta.annotation.Nullable String taskName) {
    this.taskName = taskName;
  }


  public BriefAnalysisTask calcType(@jakarta.annotation.Nullable String calcType) {
    this.calcType = calcType;
    return this;
  }

  /**
   * Get calcType
   * @return calcType
   */
  @jakarta.annotation.Nullable
  public String getCalcType() {
    return calcType;
  }

  public void setCalcType(@jakarta.annotation.Nullable String calcType) {
    this.calcType = calcType;
  }


  public BriefAnalysisTask scheduleType(@jakarta.annotation.Nullable String scheduleType) {
    this.scheduleType = scheduleType;
    return this;
  }

  /**
   * Get scheduleType
   * @return scheduleType
   */
  @jakarta.annotation.Nullable
  public String getScheduleType() {
    return scheduleType;
  }

  public void setScheduleType(@jakarta.annotation.Nullable String scheduleType) {
    this.scheduleType = scheduleType;
  }


  public BriefAnalysisTask period(@jakarta.annotation.Nullable String period) {
    this.period = period;
    return this;
  }

  /**
   * Get period
   * @return period
   */
  @jakarta.annotation.Nullable
  public String getPeriod() {
    return period;
  }

  public void setPeriod(@jakarta.annotation.Nullable String period) {
    this.period = period;
  }


  public BriefAnalysisTask enabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @jakarta.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public BriefAnalysisTask eventClassId(@jakarta.annotation.Nullable String eventClassId) {
    this.eventClassId = eventClassId;
    return this;
  }

  /**
   * Get eventClassId
   * @return eventClassId
   */
  @jakarta.annotation.Nullable
  public String getEventClassId() {
    return eventClassId;
  }

  public void setEventClassId(@jakarta.annotation.Nullable String eventClassId) {
    this.eventClassId = eventClassId;
  }


  public BriefAnalysisTask eventClassName(@jakarta.annotation.Nullable String eventClassName) {
    this.eventClassName = eventClassName;
    return this;
  }

  /**
   * Get eventClassName
   * @return eventClassName
   */
  @jakarta.annotation.Nullable
  public String getEventClassName() {
    return eventClassName;
  }

  public void setEventClassName(@jakarta.annotation.Nullable String eventClassName) {
    this.eventClassName = eventClassName;
  }


  public BriefAnalysisTask modelId(@jakarta.annotation.Nullable String modelId) {
    this.modelId = modelId;
    return this;
  }

  /**
   * Get modelId
   * @return modelId
   */
  @jakarta.annotation.Nullable
  public String getModelId() {
    return modelId;
  }

  public void setModelId(@jakarta.annotation.Nullable String modelId) {
    this.modelId = modelId;
  }


  public BriefAnalysisTask modelName(@jakarta.annotation.Nullable String modelName) {
    this.modelName = modelName;
    return this;
  }

  /**
   * Get modelName
   * @return modelName
   */
  @jakarta.annotation.Nullable
  public String getModelName() {
    return modelName;
  }

  public void setModelName(@jakarta.annotation.Nullable String modelName) {
    this.modelName = modelName;
  }


  public BriefAnalysisTask createTime(@jakarta.annotation.Nullable String createTime) {
    this.createTime = createTime;
    return this;
  }

  /**
   * Get createTime
   * @return createTime
   */
  @jakarta.annotation.Nullable
  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(@jakarta.annotation.Nullable String createTime) {
    this.createTime = createTime;
  }


  public BriefAnalysisTask updateTime(@jakarta.annotation.Nullable String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  /**
   * Get updateTime
   * @return updateTime
   */
  @jakarta.annotation.Nullable
  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(@jakarta.annotation.Nullable String updateTime) {
    this.updateTime = updateTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BriefAnalysisTask briefAnalysisTask = (BriefAnalysisTask) o;
    return Objects.equals(this.taskId, briefAnalysisTask.taskId) &&
        Objects.equals(this.taskName, briefAnalysisTask.taskName) &&
        Objects.equals(this.calcType, briefAnalysisTask.calcType) &&
        Objects.equals(this.scheduleType, briefAnalysisTask.scheduleType) &&
        Objects.equals(this.period, briefAnalysisTask.period) &&
        Objects.equals(this.enabled, briefAnalysisTask.enabled) &&
        Objects.equals(this.eventClassId, briefAnalysisTask.eventClassId) &&
        Objects.equals(this.eventClassName, briefAnalysisTask.eventClassName) &&
        Objects.equals(this.modelId, briefAnalysisTask.modelId) &&
        Objects.equals(this.modelName, briefAnalysisTask.modelName) &&
        Objects.equals(this.createTime, briefAnalysisTask.createTime) &&
        Objects.equals(this.updateTime, briefAnalysisTask.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskId, taskName, calcType, scheduleType, period, enabled, eventClassId, eventClassName, modelId, modelName, createTime, updateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BriefAnalysisTask {\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    taskName: ").append(toIndentedString(taskName)).append("\n");
    sb.append("    calcType: ").append(toIndentedString(calcType)).append("\n");
    sb.append("    scheduleType: ").append(toIndentedString(scheduleType)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    eventClassId: ").append(toIndentedString(eventClassId)).append("\n");
    sb.append("    eventClassName: ").append(toIndentedString(eventClassName)).append("\n");
    sb.append("    modelId: ").append(toIndentedString(modelId)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("task_id");
    openapiFields.add("task_name");
    openapiFields.add("calc_type");
    openapiFields.add("schedule_type");
    openapiFields.add("period");
    openapiFields.add("enabled");
    openapiFields.add("event_class_id");
    openapiFields.add("event_class_name");
    openapiFields.add("model_id");
    openapiFields.add("model_name");
    openapiFields.add("create_time");
    openapiFields.add("update_time");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BriefAnalysisTask
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BriefAnalysisTask.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BriefAnalysisTask is not found in the empty JSON string", BriefAnalysisTask.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BriefAnalysisTask.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BriefAnalysisTask` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("task_id") != null && !jsonObj.get("task_id").isJsonNull()) && !jsonObj.get("task_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `task_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("task_id").toString()));
      }
      if ((jsonObj.get("task_name") != null && !jsonObj.get("task_name").isJsonNull()) && !jsonObj.get("task_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `task_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("task_name").toString()));
      }
      if ((jsonObj.get("calc_type") != null && !jsonObj.get("calc_type").isJsonNull()) && !jsonObj.get("calc_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `calc_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("calc_type").toString()));
      }
      if ((jsonObj.get("schedule_type") != null && !jsonObj.get("schedule_type").isJsonNull()) && !jsonObj.get("schedule_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `schedule_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("schedule_type").toString()));
      }
      if ((jsonObj.get("period") != null && !jsonObj.get("period").isJsonNull()) && !jsonObj.get("period").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `period` to be a primitive type in the JSON string but got `%s`", jsonObj.get("period").toString()));
      }
      if ((jsonObj.get("event_class_id") != null && !jsonObj.get("event_class_id").isJsonNull()) && !jsonObj.get("event_class_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `event_class_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_class_id").toString()));
      }
      if ((jsonObj.get("event_class_name") != null && !jsonObj.get("event_class_name").isJsonNull()) && !jsonObj.get("event_class_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `event_class_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_class_name").toString()));
      }
      if ((jsonObj.get("model_id") != null && !jsonObj.get("model_id").isJsonNull()) && !jsonObj.get("model_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `model_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model_id").toString()));
      }
      if ((jsonObj.get("model_name") != null && !jsonObj.get("model_name").isJsonNull()) && !jsonObj.get("model_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `model_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model_name").toString()));
      }
      if ((jsonObj.get("create_time") != null && !jsonObj.get("create_time").isJsonNull()) && !jsonObj.get("create_time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `create_time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("create_time").toString()));
      }
      if ((jsonObj.get("update_time") != null && !jsonObj.get("update_time").isJsonNull()) && !jsonObj.get("update_time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `update_time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("update_time").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BriefAnalysisTask.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BriefAnalysisTask' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BriefAnalysisTask> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BriefAnalysisTask.class));

       return (TypeAdapter<T>) new TypeAdapter<BriefAnalysisTask>() {
           @Override
           public void write(JsonWriter out, BriefAnalysisTask value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BriefAnalysisTask read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BriefAnalysisTask given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BriefAnalysisTask
   * @throws IOException if the JSON string is invalid with respect to BriefAnalysisTask
   */
  public static BriefAnalysisTask fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BriefAnalysisTask.class);
  }

  /**
   * Convert an instance of BriefAnalysisTask to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

