/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OriginalReports
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-22T08:57:00.546871+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class OriginalReports {
  public static final String SERIALIZED_NAME_SYNC_TIME = "sync_time";
  @SerializedName(SERIALIZED_NAME_SYNC_TIME)
  @javax.annotation.Nullable
  private String syncTime;

  public static final String SERIALIZED_NAME_AGING_TIME = "aging_time";
  @SerializedName(SERIALIZED_NAME_AGING_TIME)
  @javax.annotation.Nullable
  private String agingTime;

  public OriginalReports() {
  }

  public OriginalReports syncTime(@javax.annotation.Nullable String syncTime) {
    this.syncTime = syncTime;
    return this;
  }

  /**
   * Get syncTime
   * @return syncTime
   */
  @javax.annotation.Nullable
  public String getSyncTime() {
    return syncTime;
  }

  public void setSyncTime(@javax.annotation.Nullable String syncTime) {
    this.syncTime = syncTime;
  }


  public OriginalReports agingTime(@javax.annotation.Nullable String agingTime) {
    this.agingTime = agingTime;
    return this;
  }

  /**
   * Get agingTime
   * @return agingTime
   */
  @javax.annotation.Nullable
  public String getAgingTime() {
    return agingTime;
  }

  public void setAgingTime(@javax.annotation.Nullable String agingTime) {
    this.agingTime = agingTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OriginalReports originalReports = (OriginalReports) o;
    return Objects.equals(this.syncTime, originalReports.syncTime) &&
        Objects.equals(this.agingTime, originalReports.agingTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(syncTime, agingTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OriginalReports {\n");
    sb.append("    syncTime: ").append(toIndentedString(syncTime)).append("\n");
    sb.append("    agingTime: ").append(toIndentedString(agingTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sync_time");
    openapiFields.add("aging_time");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OriginalReports
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OriginalReports.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OriginalReports is not found in the empty JSON string", OriginalReports.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OriginalReports.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OriginalReports` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("sync_time") != null && !jsonObj.get("sync_time").isJsonNull()) && !jsonObj.get("sync_time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sync_time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sync_time").toString()));
      }
      if ((jsonObj.get("aging_time") != null && !jsonObj.get("aging_time").isJsonNull()) && !jsonObj.get("aging_time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `aging_time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("aging_time").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OriginalReports.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OriginalReports' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OriginalReports> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OriginalReports.class));

       return (TypeAdapter<T>) new TypeAdapter<OriginalReports>() {
           @Override
           public void write(JsonWriter out, OriginalReports value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OriginalReports read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OriginalReports given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OriginalReports
   * @throws IOException if the JSON string is invalid with respect to OriginalReports
   */
  public static OriginalReports fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OriginalReports.class);
  }

  /**
   * Convert an instance of OriginalReports to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

