/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SaveRecordsRequest
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-26T20:31:18.115216+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class SaveRecordsRequest {
  public static final String SERIALIZED_NAME_COLUMNS = "columns";
  @SerializedName(SERIALIZED_NAME_COLUMNS)
  @jakarta.annotation.Nullable
  private List<String> columns = new ArrayList<>();

  public static final String SERIALIZED_NAME_VALUES = "values";
  @SerializedName(SERIALIZED_NAME_VALUES)
  @jakarta.annotation.Nullable
  private List<List<Object>> values = new ArrayList<>();

  public static final String SERIALIZED_NAME_COLUMN_VALUES = "column_values";
  @SerializedName(SERIALIZED_NAME_COLUMN_VALUES)
  @jakarta.annotation.Nullable
  private List<Object> columnValues = new ArrayList<>();

  public SaveRecordsRequest() {
  }

  public SaveRecordsRequest columns(@jakarta.annotation.Nullable List<String> columns) {
    this.columns = columns;
    return this;
  }

  public SaveRecordsRequest addColumnsItem(String columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<>();
    }
    this.columns.add(columnsItem);
    return this;
  }

  /**
   * Get columns
   * @return columns
   */
  @jakarta.annotation.Nullable
  public List<String> getColumns() {
    return columns;
  }

  public void setColumns(@jakarta.annotation.Nullable List<String> columns) {
    this.columns = columns;
  }


  public SaveRecordsRequest values(@jakarta.annotation.Nullable List<List<Object>> values) {
    this.values = values;
    return this;
  }

  public SaveRecordsRequest addValuesItem(List<Object> valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<>();
    }
    this.values.add(valuesItem);
    return this;
  }

  /**
   * Get values
   * @return values
   */
  @jakarta.annotation.Nullable
  public List<List<Object>> getValues() {
    return values;
  }

  public void setValues(@jakarta.annotation.Nullable List<List<Object>> values) {
    this.values = values;
  }


  public SaveRecordsRequest columnValues(@jakarta.annotation.Nullable List<Object> columnValues) {
    this.columnValues = columnValues;
    return this;
  }

  public SaveRecordsRequest addColumnValuesItem(Object columnValuesItem) {
    if (this.columnValues == null) {
      this.columnValues = new ArrayList<>();
    }
    this.columnValues.add(columnValuesItem);
    return this;
  }

  /**
   * Get columnValues
   * @return columnValues
   */
  @jakarta.annotation.Nullable
  public List<Object> getColumnValues() {
    return columnValues;
  }

  public void setColumnValues(@jakarta.annotation.Nullable List<Object> columnValues) {
    this.columnValues = columnValues;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaveRecordsRequest saveRecordsRequest = (SaveRecordsRequest) o;
    return Objects.equals(this.columns, saveRecordsRequest.columns) &&
        Objects.equals(this.values, saveRecordsRequest.values) &&
        Objects.equals(this.columnValues, saveRecordsRequest.columnValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columns, values, columnValues);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaveRecordsRequest {\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    columnValues: ").append(toIndentedString(columnValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("columns");
    openapiFields.add("values");
    openapiFields.add("column_values");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SaveRecordsRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SaveRecordsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SaveRecordsRequest is not found in the empty JSON string", SaveRecordsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SaveRecordsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SaveRecordsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("columns") != null && !jsonObj.get("columns").isJsonNull() && !jsonObj.get("columns").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `columns` to be an array in the JSON string but got `%s`", jsonObj.get("columns").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("values") != null && !jsonObj.get("values").isJsonNull() && !jsonObj.get("values").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `values` to be an array in the JSON string but got `%s`", jsonObj.get("values").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("column_values") != null && !jsonObj.get("column_values").isJsonNull() && !jsonObj.get("column_values").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `column_values` to be an array in the JSON string but got `%s`", jsonObj.get("column_values").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SaveRecordsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SaveRecordsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SaveRecordsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SaveRecordsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SaveRecordsRequest>() {
           @Override
           public void write(JsonWriter out, SaveRecordsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SaveRecordsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SaveRecordsRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SaveRecordsRequest
   * @throws IOException if the JSON string is invalid with respect to SaveRecordsRequest
   */
  public static SaveRecordsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SaveRecordsRequest.class);
  }

  /**
   * Convert an instance of SaveRecordsRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

