/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ThingDTO
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-26T20:45:51.998201+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class ThingDTO {
  public static final String SERIALIZED_NAME_THING_ID = "thing_id";
  @SerializedName(SERIALIZED_NAME_THING_ID)
  @jakarta.annotation.Nullable
  private String thingId;

  public static final String SERIALIZED_NAME_THING_NAME = "thing_name";
  @SerializedName(SERIALIZED_NAME_THING_NAME)
  @jakarta.annotation.Nullable
  private String thingName;

  public static final String SERIALIZED_NAME_MODEL_ID = "model_id";
  @SerializedName(SERIALIZED_NAME_MODEL_ID)
  @jakarta.annotation.Nullable
  private String modelId;

  public static final String SERIALIZED_NAME_MODEL_NAME = "model_name";
  @SerializedName(SERIALIZED_NAME_MODEL_NAME)
  @jakarta.annotation.Nullable
  private String modelName;

  public ThingDTO() {
  }

  public ThingDTO thingId(@jakarta.annotation.Nullable String thingId) {
    this.thingId = thingId;
    return this;
  }

  /**
   * Get thingId
   * @return thingId
   */
  @jakarta.annotation.Nullable
  public String getThingId() {
    return thingId;
  }

  public void setThingId(@jakarta.annotation.Nullable String thingId) {
    this.thingId = thingId;
  }


  public ThingDTO thingName(@jakarta.annotation.Nullable String thingName) {
    this.thingName = thingName;
    return this;
  }

  /**
   * Get thingName
   * @return thingName
   */
  @jakarta.annotation.Nullable
  public String getThingName() {
    return thingName;
  }

  public void setThingName(@jakarta.annotation.Nullable String thingName) {
    this.thingName = thingName;
  }


  public ThingDTO modelId(@jakarta.annotation.Nullable String modelId) {
    this.modelId = modelId;
    return this;
  }

  /**
   * Get modelId
   * @return modelId
   */
  @jakarta.annotation.Nullable
  public String getModelId() {
    return modelId;
  }

  public void setModelId(@jakarta.annotation.Nullable String modelId) {
    this.modelId = modelId;
  }


  public ThingDTO modelName(@jakarta.annotation.Nullable String modelName) {
    this.modelName = modelName;
    return this;
  }

  /**
   * Get modelName
   * @return modelName
   */
  @jakarta.annotation.Nullable
  public String getModelName() {
    return modelName;
  }

  public void setModelName(@jakarta.annotation.Nullable String modelName) {
    this.modelName = modelName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThingDTO thingDTO = (ThingDTO) o;
    return Objects.equals(this.thingId, thingDTO.thingId) &&
        Objects.equals(this.thingName, thingDTO.thingName) &&
        Objects.equals(this.modelId, thingDTO.modelId) &&
        Objects.equals(this.modelName, thingDTO.modelName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(thingId, thingName, modelId, modelName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThingDTO {\n");
    sb.append("    thingId: ").append(toIndentedString(thingId)).append("\n");
    sb.append("    thingName: ").append(toIndentedString(thingName)).append("\n");
    sb.append("    modelId: ").append(toIndentedString(modelId)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("thing_id");
    openapiFields.add("thing_name");
    openapiFields.add("model_id");
    openapiFields.add("model_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ThingDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ThingDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ThingDTO is not found in the empty JSON string", ThingDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ThingDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ThingDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("thing_id") != null && !jsonObj.get("thing_id").isJsonNull()) && !jsonObj.get("thing_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `thing_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("thing_id").toString()));
      }
      if ((jsonObj.get("thing_name") != null && !jsonObj.get("thing_name").isJsonNull()) && !jsonObj.get("thing_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `thing_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("thing_name").toString()));
      }
      if ((jsonObj.get("model_id") != null && !jsonObj.get("model_id").isJsonNull()) && !jsonObj.get("model_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `model_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model_id").toString()));
      }
      if ((jsonObj.get("model_name") != null && !jsonObj.get("model_name").isJsonNull()) && !jsonObj.get("model_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `model_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ThingDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ThingDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ThingDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ThingDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<ThingDTO>() {
           @Override
           public void write(JsonWriter out, ThingDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ThingDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ThingDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ThingDTO
   * @throws IOException if the JSON string is invalid with respect to ThingDTO
   */
  public static ThingDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ThingDTO.class);
  }

  /**
   * Convert an instance of ThingDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

