/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertiesGetReq } from './PropertiesGetReq';
import {
    PropertiesGetReqFromJSON,
    PropertiesGetReqFromJSONTyped,
    PropertiesGetReqToJSON,
    PropertiesGetReqToJSONTyped,
} from './PropertiesGetReq';

/**
 * 
 * @export
 * @interface BatchListThingSnapshotsReqThingsInner
 */
export interface BatchListThingSnapshotsReqThingsInner {
    /**
     * 
     * @type {string}
     * @memberof BatchListThingSnapshotsReqThingsInner
     */
    thingId: string;
    /**
     * 
     * @type {{ [key: string]: PropertiesGetReq; }}
     * @memberof BatchListThingSnapshotsReqThingsInner
     */
    components?: { [key: string]: PropertiesGetReq; };
}

/**
 * Check if a given object implements the BatchListThingSnapshotsReqThingsInner interface.
 */
export function instanceOfBatchListThingSnapshotsReqThingsInner(value: object): value is BatchListThingSnapshotsReqThingsInner {
    if (!('thingId' in value) || value['thingId'] === undefined) return false;
    return true;
}

export function BatchListThingSnapshotsReqThingsInnerFromJSON(json: any): BatchListThingSnapshotsReqThingsInner {
    return BatchListThingSnapshotsReqThingsInnerFromJSONTyped(json, false);
}

export function BatchListThingSnapshotsReqThingsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchListThingSnapshotsReqThingsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'thingId': json['thing_id'],
        'components': json['components'] == null ? undefined : (mapValues(json['components'], PropertiesGetReqFromJSON)),
    };
}

export function BatchListThingSnapshotsReqThingsInnerToJSON(json: any): BatchListThingSnapshotsReqThingsInner {
    return BatchListThingSnapshotsReqThingsInnerToJSONTyped(json, false);
}

export function BatchListThingSnapshotsReqThingsInnerToJSONTyped(value?: BatchListThingSnapshotsReqThingsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thing_id': value['thingId'],
        'components': value['components'] == null ? undefined : (mapValues(value['components'], PropertiesGetReqToJSON)),
    };
}

