/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyValueObject } from './PropertyValueObject';
import {
    PropertyValueObjectFromJSON,
    PropertyValueObjectFromJSONTyped,
    PropertyValueObjectToJSON,
    PropertyValueObjectToJSONTyped,
} from './PropertyValueObject';

/**
 * 
 * @export
 * @interface ComponentProperty
 */
export interface ComponentProperty {
    /**
     * 
     * @type {{ [key: string]: PropertyValueObject; }}
     * @memberof ComponentProperty
     */
    properties?: { [key: string]: PropertyValueObject; };
    /**
     * 
     * @type {{ [key: string]: ComponentProperty; }}
     * @memberof ComponentProperty
     */
    components?: { [key: string]: ComponentProperty; };
}

/**
 * Check if a given object implements the ComponentProperty interface.
 */
export function instanceOfComponentProperty(value: object): value is ComponentProperty {
    return true;
}

export function ComponentPropertyFromJSON(json: any): ComponentProperty {
    return ComponentPropertyFromJSONTyped(json, false);
}

export function ComponentPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComponentProperty {
    if (json == null) {
        return json;
    }
    return {
        
        'properties': json['properties'] == null ? undefined : (mapValues(json['properties'], PropertyValueObjectFromJSON)),
        'components': json['components'] == null ? undefined : (mapValues(json['components'], ComponentPropertyFromJSON)),
    };
}

export function ComponentPropertyToJSON(json: any): ComponentProperty {
    return ComponentPropertyToJSONTyped(json, false);
}

export function ComponentPropertyToJSONTyped(value?: ComponentProperty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'properties': value['properties'] == null ? undefined : (mapValues(value['properties'], PropertyValueObjectToJSON)),
        'components': value['components'] == null ? undefined : (mapValues(value['components'], ComponentPropertyToJSON)),
    };
}

