/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgingSettings } from './AgingSettings';
import {
    AgingSettingsFromJSON,
    AgingSettingsFromJSONTyped,
    AgingSettingsToJSON,
    AgingSettingsToJSONTyped,
} from './AgingSettings';
import type { TableSchema } from './TableSchema';
import {
    TableSchemaFromJSON,
    TableSchemaFromJSONTyped,
    TableSchemaToJSON,
    TableSchemaToJSONTyped,
} from './TableSchema';

/**
 * 
 * @export
 * @interface CreateTableRequest
 */
export interface CreateTableRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTableRequest
     */
    tableId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTableRequest
     */
    tableName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTableRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTableRequest
     */
    catalogId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTableRequest
     */
    description?: string;
    /**
     * 
     * @type {TableSchema}
     * @memberof CreateTableRequest
     */
    tableSchema: TableSchema;
    /**
     * 
     * @type {AgingSettings}
     * @memberof CreateTableRequest
     */
    agingSettings?: AgingSettings;
}

/**
 * Check if a given object implements the CreateTableRequest interface.
 */
export function instanceOfCreateTableRequest(value: object): value is CreateTableRequest {
    if (!('tableId' in value) || value['tableId'] === undefined) return false;
    if (!('tableName' in value) || value['tableName'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('tableSchema' in value) || value['tableSchema'] === undefined) return false;
    return true;
}

export function CreateTableRequestFromJSON(json: any): CreateTableRequest {
    return CreateTableRequestFromJSONTyped(json, false);
}

export function CreateTableRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTableRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tableId': json['table_id'],
        'tableName': json['table_name'],
        'type': json['type'],
        'catalogId': json['catalog_id'] == null ? undefined : json['catalog_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'tableSchema': TableSchemaFromJSON(json['table_schema']),
        'agingSettings': json['aging_settings'] == null ? undefined : AgingSettingsFromJSON(json['aging_settings']),
    };
}

export function CreateTableRequestToJSON(json: any): CreateTableRequest {
    return CreateTableRequestToJSONTyped(json, false);
}

export function CreateTableRequestToJSONTyped(value?: CreateTableRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'table_id': value['tableId'],
        'table_name': value['tableName'],
        'type': value['type'],
        'catalog_id': value['catalogId'],
        'description': value['description'],
        'table_schema': TableSchemaToJSON(value['tableSchema']),
        'aging_settings': AgingSettingsToJSON(value['agingSettings']),
    };
}

