/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyValue } from './PropertyValue';
import {
    PropertyValueFromJSON,
    PropertyValueFromJSONTyped,
    PropertyValueToJSON,
    PropertyValueToJSONTyped,
} from './PropertyValue';

/**
 * 
 * @export
 * @interface CreateThingRequest
 */
export interface CreateThingRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateThingRequest
     */
    thingId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateThingRequest
     */
    thingName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateThingRequest
     */
    modelId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateThingRequest
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: PropertyValue; }}
     * @memberof CreateThingRequest
     */
    properties?: { [key: string]: PropertyValue; };
}

/**
 * Check if a given object implements the CreateThingRequest interface.
 */
export function instanceOfCreateThingRequest(value: object): value is CreateThingRequest {
    if (!('thingId' in value) || value['thingId'] === undefined) return false;
    if (!('thingName' in value) || value['thingName'] === undefined) return false;
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    return true;
}

export function CreateThingRequestFromJSON(json: any): CreateThingRequest {
    return CreateThingRequestFromJSONTyped(json, false);
}

export function CreateThingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateThingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'thingId': json['thing_id'],
        'thingName': json['thing_name'],
        'modelId': json['model_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'properties': json['properties'] == null ? undefined : (mapValues(json['properties'], PropertyValueFromJSON)),
    };
}

export function CreateThingRequestToJSON(json: any): CreateThingRequest {
    return CreateThingRequestToJSONTyped(json, false);
}

export function CreateThingRequestToJSONTyped(value?: CreateThingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thing_id': value['thingId'],
        'thing_name': value['thingName'],
        'model_id': value['modelId'],
        'description': value['description'],
        'properties': value['properties'] == null ? undefined : (mapValues(value['properties'], PropertyValueToJSON)),
    };
}

