/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateViewReq
 */
export interface CreateViewReq {
    /**
     * 
     * @type {string}
     * @memberof CreateViewReq
     */
    viewId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateViewReq
     */
    viewName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateViewReq
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateViewReq interface.
 */
export function instanceOfCreateViewReq(value: object): value is CreateViewReq {
    if (!('viewId' in value) || value['viewId'] === undefined) return false;
    if (!('viewName' in value) || value['viewName'] === undefined) return false;
    return true;
}

export function CreateViewReqFromJSON(json: any): CreateViewReq {
    return CreateViewReqFromJSONTyped(json, false);
}

export function CreateViewReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateViewReq {
    if (json == null) {
        return json;
    }
    return {
        
        'viewId': json['view_id'],
        'viewName': json['view_name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateViewReqToJSON(json: any): CreateViewReq {
    return CreateViewReqToJSONTyped(json, false);
}

export function CreateViewReqToJSONTyped(value?: CreateViewReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'view_id': value['viewId'],
        'view_name': value['viewName'],
        'description': value['description'],
    };
}

