/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DicItem
 */
export interface DicItem {
    /**
     * 
     * @type {string}
     * @memberof DicItem
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof DicItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DicItem
     */
    description?: string;
}

/**
 * Check if a given object implements the DicItem interface.
 */
export function instanceOfDicItem(value: object): value is DicItem {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DicItemFromJSON(json: any): DicItem {
    return DicItemFromJSONTyped(json, false);
}

export function DicItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DicItem {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function DicItemToJSON(json: any): DicItem {
    return DicItemToJSONTyped(json, false);
}

export function DicItemToJSONTyped(value?: DicItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'name': value['name'],
        'description': value['description'],
    };
}

