/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DicItem } from './DicItem';
import {
    DicItemFromJSON,
    DicItemFromJSONTyped,
    DicItemToJSON,
    DicItemToJSONTyped,
} from './DicItem';

/**
 * 
 * @export
 * @interface Dictionary
 */
export interface Dictionary {
    /**
     * 
     * @type {string}
     * @memberof Dictionary
     */
    dicId: string;
    /**
     * 
     * @type {string}
     * @memberof Dictionary
     */
    dicName: string;
    /**
     * 
     * @type {string}
     * @memberof Dictionary
     */
    dataType: string;
    /**
     * 
     * @type {string}
     * @memberof Dictionary
     */
    catalogId: string;
    /**
     * 
     * @type {Array<DicItem>}
     * @memberof Dictionary
     */
    values: Array<DicItem>;
    /**
     * 
     * @type {string}
     * @memberof Dictionary
     */
    createTime: string;
    /**
     * 
     * @type {string}
     * @memberof Dictionary
     */
    updateTime: string;
}

/**
 * Check if a given object implements the Dictionary interface.
 */
export function instanceOfDictionary(value: object): value is Dictionary {
    if (!('dicId' in value) || value['dicId'] === undefined) return false;
    if (!('dicName' in value) || value['dicName'] === undefined) return false;
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    if (!('catalogId' in value) || value['catalogId'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    if (!('updateTime' in value) || value['updateTime'] === undefined) return false;
    return true;
}

export function DictionaryFromJSON(json: any): Dictionary {
    return DictionaryFromJSONTyped(json, false);
}

export function DictionaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dictionary {
    if (json == null) {
        return json;
    }
    return {
        
        'dicId': json['dic_id'],
        'dicName': json['dic_name'],
        'dataType': json['data_type'],
        'catalogId': json['catalog_id'],
        'values': ((json['values'] as Array<any>).map(DicItemFromJSON)),
        'createTime': json['create_time'],
        'updateTime': json['update_time'],
    };
}

export function DictionaryToJSON(json: any): Dictionary {
    return DictionaryToJSONTyped(json, false);
}

export function DictionaryToJSONTyped(value?: Dictionary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dic_id': value['dicId'],
        'dic_name': value['dicName'],
        'data_type': value['dataType'],
        'catalog_id': value['catalogId'],
        'values': ((value['values'] as Array<any>).map(DicItemToJSON)),
        'create_time': value['createTime'],
        'update_time': value['updateTime'],
    };
}

