/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDeviceRespDTO
 */
export interface GetDeviceRespDTO {
    /**
     * 
     * @type {string}
     * @memberof GetDeviceRespDTO
     */
    deviceId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetDeviceRespDTO
     */
    deviceName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetDeviceRespDTO
     */
    deviceType?: string;
    /**
     * 
     * @type {string}
     * @memberof GetDeviceRespDTO
     */
    deviceStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof GetDeviceRespDTO
     */
    createTime?: string;
    /**
     * 
     * @type {string}
     * @memberof GetDeviceRespDTO
     */
    updateTime?: string;
}

/**
 * Check if a given object implements the GetDeviceRespDTO interface.
 */
export function instanceOfGetDeviceRespDTO(value: object): value is GetDeviceRespDTO {
    return true;
}

export function GetDeviceRespDTOFromJSON(json: any): GetDeviceRespDTO {
    return GetDeviceRespDTOFromJSONTyped(json, false);
}

export function GetDeviceRespDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDeviceRespDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['device_id'] == null ? undefined : json['device_id'],
        'deviceName': json['device_name'] == null ? undefined : json['device_name'],
        'deviceType': json['device_type'] == null ? undefined : json['device_type'],
        'deviceStatus': json['device_status'] == null ? undefined : json['device_status'],
        'createTime': json['create_time'] == null ? undefined : json['create_time'],
        'updateTime': json['update_time'] == null ? undefined : json['update_time'],
    };
}

export function GetDeviceRespDTOToJSON(json: any): GetDeviceRespDTO {
    return GetDeviceRespDTOToJSONTyped(json, false);
}

export function GetDeviceRespDTOToJSONTyped(value?: GetDeviceRespDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device_id': value['deviceId'],
        'device_name': value['deviceName'],
        'device_type': value['deviceType'],
        'device_status': value['deviceStatus'],
        'create_time': value['createTime'],
        'update_time': value['updateTime'],
    };
}

