/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegratedReports
 */
export interface IntegratedReports {
    /**
     * 
     * @type {string}
     * @memberof IntegratedReports
     */
    integratedTime?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegratedReports
     */
    agingTime?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegratedReports
     */
    integratedStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegratedReports
     */
    integratedResult?: string;
}

/**
 * Check if a given object implements the IntegratedReports interface.
 */
export function instanceOfIntegratedReports(value: object): value is IntegratedReports {
    return true;
}

export function IntegratedReportsFromJSON(json: any): IntegratedReports {
    return IntegratedReportsFromJSONTyped(json, false);
}

export function IntegratedReportsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegratedReports {
    if (json == null) {
        return json;
    }
    return {
        
        'integratedTime': json['integrated_time'] == null ? undefined : json['integrated_time'],
        'agingTime': json['aging_time'] == null ? undefined : json['aging_time'],
        'integratedStatus': json['integrated_status'] == null ? undefined : json['integrated_status'],
        'integratedResult': json['integrated_result'] == null ? undefined : json['integrated_result'],
    };
}

export function IntegratedReportsToJSON(json: any): IntegratedReports {
    return IntegratedReportsToJSONTyped(json, false);
}

export function IntegratedReportsToJSONTyped(value?: IntegratedReports | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'integrated_time': value['integratedTime'],
        'aging_time': value['agingTime'],
        'integrated_status': value['integratedStatus'],
        'integrated_result': value['integratedResult'],
    };
}

