/* tslint:disable */
/* eslint-disable */
/**
 * Model API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegerSchema
 */
export interface IntegerSchema {
    /**
     * 
     * @type {number}
     * @memberof IntegerSchema
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof IntegerSchema
     */
    max?: number;
}

/**
 * Check if a given object implements the IntegerSchema interface.
 */
export function instanceOfIntegerSchema(value: object): value is IntegerSchema {
    return true;
}

export function IntegerSchemaFromJSON(json: any): IntegerSchema {
    return IntegerSchemaFromJSONTyped(json, false);
}

export function IntegerSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegerSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
    };
}

export function IntegerSchemaToJSON(json: any): IntegerSchema {
    return IntegerSchemaToJSONTyped(json, false);
}

export function IntegerSchemaToJSONTyped(value?: IntegerSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min': value['min'],
        'max': value['max'],
    };
}

