/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceDTO } from './DeviceDTO';
import {
    DeviceDTOFromJSON,
    DeviceDTOFromJSONTyped,
    DeviceDTOToJSON,
    DeviceDTOToJSONTyped,
} from './DeviceDTO';

/**
 * 
 * @export
 * @interface ListDevicesDTO
 */
export interface ListDevicesDTO {
    /**
     * 
     * @type {Array<DeviceDTO>}
     * @memberof ListDevicesDTO
     */
    devices?: Array<DeviceDTO>;
    /**
     * 
     * @type {number}
     * @memberof ListDevicesDTO
     */
    count?: number;
}

/**
 * Check if a given object implements the ListDevicesDTO interface.
 */
export function instanceOfListDevicesDTO(value: object): value is ListDevicesDTO {
    return true;
}

export function ListDevicesDTOFromJSON(json: any): ListDevicesDTO {
    return ListDevicesDTOFromJSONTyped(json, false);
}

export function ListDevicesDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDevicesDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'devices': json['devices'] == null ? undefined : ((json['devices'] as Array<any>).map(DeviceDTOFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function ListDevicesDTOToJSON(json: any): ListDevicesDTO {
    return ListDevicesDTOToJSONTyped(json, false);
}

export function ListDevicesDTOToJSONTyped(value?: ListDevicesDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'devices': value['devices'] == null ? undefined : ((value['devices'] as Array<any>).map(DeviceDTOToJSON)),
        'count': value['count'],
    };
}

