/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OtstatReports
 */
export interface OtstatReports {
    /**
     * 
     * @type {string}
     * @memberof OtstatReports
     */
    statTime?: string;
    /**
     * 
     * @type {string}
     * @memberof OtstatReports
     */
    agingTime?: string;
    /**
     * 
     * @type {string}
     * @memberof OtstatReports
     */
    statStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof OtstatReports
     */
    statResult?: string;
}

/**
 * Check if a given object implements the OtstatReports interface.
 */
export function instanceOfOtstatReports(value: object): value is OtstatReports {
    return true;
}

export function OtstatReportsFromJSON(json: any): OtstatReports {
    return OtstatReportsFromJSONTyped(json, false);
}

export function OtstatReportsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtstatReports {
    if (json == null) {
        return json;
    }
    return {
        
        'statTime': json['stat_time'] == null ? undefined : json['stat_time'],
        'agingTime': json['aging_time'] == null ? undefined : json['aging_time'],
        'statStatus': json['stat_status'] == null ? undefined : json['stat_status'],
        'statResult': json['stat_result'] == null ? undefined : json['stat_result'],
    };
}

export function OtstatReportsToJSON(json: any): OtstatReports {
    return OtstatReportsToJSONTyped(json, false);
}

export function OtstatReportsToJSONTyped(value?: OtstatReports | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stat_time': value['statTime'],
        'aging_time': value['agingTime'],
        'stat_status': value['statStatus'],
        'stat_result': value['statResult'],
    };
}

