/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropOutputExpression
 */
export interface PropOutputExpression {
    /**
     * 
     * @type {string}
     * @memberof PropOutputExpression
     */
    expression: string;
    /**
     * 
     * @type {string}
     * @memberof PropOutputExpression
     */
    propertyPath: string;
}

/**
 * Check if a given object implements the PropOutputExpression interface.
 */
export function instanceOfPropOutputExpression(value: object): value is PropOutputExpression {
    if (!('expression' in value) || value['expression'] === undefined) return false;
    if (!('propertyPath' in value) || value['propertyPath'] === undefined) return false;
    return true;
}

export function PropOutputExpressionFromJSON(json: any): PropOutputExpression {
    return PropOutputExpressionFromJSONTyped(json, false);
}

export function PropOutputExpressionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropOutputExpression {
    if (json == null) {
        return json;
    }
    return {
        
        'expression': json['expression'],
        'propertyPath': json['property_path'],
    };
}

export function PropOutputExpressionToJSON(json: any): PropOutputExpression {
    return PropOutputExpressionToJSONTyped(json, false);
}

export function PropOutputExpressionToJSONTyped(value?: PropOutputExpression | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expression': value['expression'],
        'property_path': value['propertyPath'],
    };
}

