/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryViewNodesReq
 */
export interface QueryViewNodesReq {
    /**
     * 
     * @type {string}
     * @memberof QueryViewNodesReq
     */
    nodeId?: string;
}

/**
 * Check if a given object implements the QueryViewNodesReq interface.
 */
export function instanceOfQueryViewNodesReq(value: object): value is QueryViewNodesReq {
    return true;
}

export function QueryViewNodesReqFromJSON(json: any): QueryViewNodesReq {
    return QueryViewNodesReqFromJSONTyped(json, false);
}

export function QueryViewNodesReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryViewNodesReq {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeId': json['node_id'] == null ? undefined : json['node_id'],
    };
}

export function QueryViewNodesReqToJSON(json: any): QueryViewNodesReq {
    return QueryViewNodesReqToJSONTyped(json, false);
}

export function QueryViewNodesReqToJSONTyped(value?: QueryViewNodesReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node_id': value['nodeId'],
    };
}

