/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StringSchema
 */
export interface StringSchema {
    /**
     * 
     * @type {number}
     * @memberof StringSchema
     */
    minLength?: number;
    /**
     * 
     * @type {number}
     * @memberof StringSchema
     */
    maxLength?: number;
}

/**
 * Check if a given object implements the StringSchema interface.
 */
export function instanceOfStringSchema(value: object): value is StringSchema {
    return true;
}

export function StringSchemaFromJSON(json: any): StringSchema {
    return StringSchemaFromJSONTyped(json, false);
}

export function StringSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'minLength': json['min_length'] == null ? undefined : json['min_length'],
        'maxLength': json['max_length'] == null ? undefined : json['max_length'],
    };
}

export function StringSchemaToJSON(json: any): StringSchema {
    return StringSchemaToJSONTyped(json, false);
}

export function StringSchemaToJSONTyped(value?: StringSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_length': value['minLength'],
        'max_length': value['maxLength'],
    };
}

