/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TableRecords
 */
export interface TableRecords {
    /**
     * 
     * @type {number}
     * @memberof TableRecords
     */
    count?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof TableRecords
     */
    columns?: Array<string>;
    /**
     * 
     * @type {Array<Array<object>>}
     * @memberof TableRecords
     */
    values?: Array<Array<object>>;
}

/**
 * Check if a given object implements the TableRecords interface.
 */
export function instanceOfTableRecords(value: object): value is TableRecords {
    return true;
}

export function TableRecordsFromJSON(json: any): TableRecords {
    return TableRecordsFromJSONTyped(json, false);
}

export function TableRecordsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableRecords {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'columns': json['columns'] == null ? undefined : json['columns'],
        'values': json['values'] == null ? undefined : json['values'],
    };
}

export function TableRecordsToJSON(json: any): TableRecords {
    return TableRecordsToJSONTyped(json, false);
}

export function TableRecordsToJSONTyped(value?: TableRecords | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'columns': value['columns'],
        'values': value['values'],
    };
}

