/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceConfDto } from './ReferenceConfDto';
import {
    ReferenceConfDtoFromJSON,
    ReferenceConfDtoFromJSONTyped,
    ReferenceConfDtoToJSON,
    ReferenceConfDtoToJSONTyped,
} from './ReferenceConfDto';
import type { ComponentReferenceConfDto } from './ComponentReferenceConfDto';
import {
    ComponentReferenceConfDtoFromJSON,
    ComponentReferenceConfDtoFromJSONTyped,
    ComponentReferenceConfDtoToJSON,
    ComponentReferenceConfDtoToJSONTyped,
} from './ComponentReferenceConfDto';

/**
 * 
 * @export
 * @interface Thing
 */
export interface Thing {
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    thingId: string;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    thingName: string;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    modelId: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Thing
     */
    tags?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: ReferenceConfDto; }}
     * @memberof Thing
     */
    properties?: { [key: string]: ReferenceConfDto; };
    /**
     * 
     * @type {{ [key: string]: ComponentReferenceConfDto; }}
     * @memberof Thing
     */
    components?: { [key: string]: ComponentReferenceConfDto; };
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    createdTime?: string;
    /**
     * 
     * @type {string}
     * @memberof Thing
     */
    updatedTime?: string;
}

/**
 * Check if a given object implements the Thing interface.
 */
export function instanceOfThing(value: object): value is Thing {
    if (!('thingId' in value) || value['thingId'] === undefined) return false;
    if (!('thingName' in value) || value['thingName'] === undefined) return false;
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    return true;
}

export function ThingFromJSON(json: any): Thing {
    return ThingFromJSONTyped(json, false);
}

export function ThingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Thing {
    if (json == null) {
        return json;
    }
    return {
        
        'thingId': json['thing_id'],
        'thingName': json['thing_name'],
        'modelId': json['model_id'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'description': json['description'] == null ? undefined : json['description'],
        'properties': json['properties'] == null ? undefined : (mapValues(json['properties'], ReferenceConfDtoFromJSON)),
        'components': json['components'] == null ? undefined : (mapValues(json['components'], ComponentReferenceConfDtoFromJSON)),
        'createdTime': json['created_time'] == null ? undefined : json['created_time'],
        'updatedTime': json['updated_time'] == null ? undefined : json['updated_time'],
    };
}

export function ThingToJSON(json: any): Thing {
    return ThingToJSONTyped(json, false);
}

export function ThingToJSONTyped(value?: Thing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thing_id': value['thingId'],
        'thing_name': value['thingName'],
        'model_id': value['modelId'],
        'tags': value['tags'],
        'description': value['description'],
        'properties': value['properties'] == null ? undefined : (mapValues(value['properties'], ReferenceConfDtoToJSON)),
        'components': value['components'] == null ? undefined : (mapValues(value['components'], ComponentReferenceConfDtoToJSON)),
        'created_time': value['createdTime'],
        'updated_time': value['updatedTime'],
    };
}

