/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComponentReferenceConfDetails } from './ComponentReferenceConfDetails';
import {
    ComponentReferenceConfDetailsFromJSON,
    ComponentReferenceConfDetailsFromJSONTyped,
    ComponentReferenceConfDetailsToJSON,
    ComponentReferenceConfDetailsToJSONTyped,
} from './ComponentReferenceConfDetails';
import type { ReferenceConfDetails } from './ReferenceConfDetails';
import {
    ReferenceConfDetailsFromJSON,
    ReferenceConfDetailsFromJSONTyped,
    ReferenceConfDetailsToJSON,
    ReferenceConfDetailsToJSONTyped,
} from './ReferenceConfDetails';
import type { PropertyValue } from './PropertyValue';
import {
    PropertyValueFromJSON,
    PropertyValueFromJSONTyped,
    PropertyValueToJSON,
    PropertyValueToJSONTyped,
} from './PropertyValue';

/**
 * 
 * @export
 * @interface UpdateThingRequest
 */
export interface UpdateThingRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateThingRequest
     */
    thingName?: string;
    /**
     * 
     * @type {{ [key: string]: PropertyValue; }}
     * @memberof UpdateThingRequest
     */
    tags?: { [key: string]: PropertyValue; };
    /**
     * 
     * @type {ReferenceConfDetails}
     * @memberof UpdateThingRequest
     */
    properties?: ReferenceConfDetails;
    /**
     * 
     * @type {ComponentReferenceConfDetails}
     * @memberof UpdateThingRequest
     */
    components?: ComponentReferenceConfDetails;
    /**
     * 
     * @type {string}
     * @memberof UpdateThingRequest
     */
    createTime?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateThingRequest
     */
    updateTime?: string;
}

/**
 * Check if a given object implements the UpdateThingRequest interface.
 */
export function instanceOfUpdateThingRequest(value: object): value is UpdateThingRequest {
    return true;
}

export function UpdateThingRequestFromJSON(json: any): UpdateThingRequest {
    return UpdateThingRequestFromJSONTyped(json, false);
}

export function UpdateThingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateThingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'thingName': json['thing_name'] == null ? undefined : json['thing_name'],
        'tags': json['tags'] == null ? undefined : (mapValues(json['tags'], PropertyValueFromJSON)),
        'properties': json['properties'] == null ? undefined : json['properties'],
        'components': json['components'] == null ? undefined : json['components'],
        'createTime': json['create_time'] == null ? undefined : json['create_time'],
        'updateTime': json['update_time'] == null ? undefined : json['update_time'],
    };
}

export function UpdateThingRequestToJSON(json: any): UpdateThingRequest {
    return UpdateThingRequestToJSONTyped(json, false);
}

export function UpdateThingRequestToJSONTyped(value?: UpdateThingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thing_name': value['thingName'],
        'tags': value['tags'] == null ? undefined : (mapValues(value['tags'], PropertyValueToJSON)),
        'properties': value['properties'],
        'components': value['components'],
        'create_time': value['createTime'],
        'update_time': value['updateTime'],
    };
}

