/*
 * IIoT OpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BriefTable {
    #[serde(rename = "table_id", skip_serializing_if = "Option::is_none")]
    pub table_id: Option<String>,
    #[serde(rename = "table_name", skip_serializing_if = "Option::is_none")]
    pub table_name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "catalog_id", skip_serializing_if = "Option::is_none")]
    pub catalog_id: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "create_time", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
    #[serde(rename = "original_reports", skip_serializing_if = "Option::is_none")]
    pub original_reports: Option<Box<models::OriginalReports>>,
    #[serde(rename = "integrated_reports", skip_serializing_if = "Option::is_none")]
    pub integrated_reports: Option<Box<models::IntegratedReports>>,
    #[serde(rename = "itstat_reports", skip_serializing_if = "Option::is_none")]
    pub itstat_reports: Option<Box<models::ItStatReports>>,
    #[serde(rename = "otstat_reports", skip_serializing_if = "Option::is_none")]
    pub otstat_reports: Option<Box<models::OtstatReports>>,
    #[serde(rename = "process_settings", skip_serializing_if = "Option::is_none")]
    pub process_settings: Option<Box<models::BriefProcessSettings>>,
}

impl BriefTable {
    pub fn new() -> BriefTable {
        BriefTable {
            table_id: None,
            table_name: None,
            r#type: None,
            catalog_id: None,
            description: None,
            create_time: None,
            update_time: None,
            original_reports: None,
            integrated_reports: None,
            itstat_reports: None,
            otstat_reports: None,
            process_settings: None,
        }
    }
}

