/*
 * IIoT OpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BriefAnalysisTask {
    #[serde(rename = "task_id", skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,
    #[serde(rename = "task_name", skip_serializing_if = "Option::is_none")]
    pub task_name: Option<String>,
    #[serde(rename = "calc_type", skip_serializing_if = "Option::is_none")]
    pub calc_type: Option<String>,
    #[serde(rename = "schedule_type", skip_serializing_if = "Option::is_none")]
    pub schedule_type: Option<String>,
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "event_class_id", skip_serializing_if = "Option::is_none")]
    pub event_class_id: Option<String>,
    #[serde(rename = "event_class_name", skip_serializing_if = "Option::is_none")]
    pub event_class_name: Option<String>,
    #[serde(rename = "model_id", skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(rename = "model_name", skip_serializing_if = "Option::is_none")]
    pub model_name: Option<String>,
    #[serde(rename = "create_time", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
}

impl BriefAnalysisTask {
    pub fn new() -> BriefAnalysisTask {
        BriefAnalysisTask {
            task_id: None,
            task_name: None,
            calc_type: None,
            schedule_type: None,
            period: None,
            enabled: None,
            event_class_id: None,
            event_class_name: None,
            model_id: None,
            model_name: None,
            create_time: None,
            update_time: None,
        }
    }
}

