/*
 * IIoT OpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CleanSettings {
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    #[serde(rename = "expressions", deserialize_with = "Option::deserialize")]
    pub expressions: Option<serde_json::Value>,
}

impl CleanSettings {
    pub fn new(expressions: Option<serde_json::Value>) -> CleanSettings {
        CleanSettings {
            condition: None,
            expressions,
        }
    }
}

