/*
 * IIoT OpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventGenAnalysisSettingsDto {
    #[serde(rename = "event_class", skip_serializing_if = "Option::is_none")]
    pub event_class: Option<String>,
    #[serde(rename = "event_gen_settings", skip_serializing_if = "Option::is_none")]
    pub event_gen_settings: Option<Box<models::EventGenSetting>>,
}

impl EventGenAnalysisSettingsDto {
    pub fn new() -> EventGenAnalysisSettingsDto {
        EventGenAnalysisSettingsDto {
            event_class: None,
            event_gen_settings: None,
        }
    }
}

