/*
 * IIoT OpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListModelsResp {
    #[serde(rename = "models", skip_serializing_if = "Option::is_none")]
    pub models: Option<Vec<models::BriefModel>>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl ListModelsResp {
    pub fn new() -> ListModelsResp {
        ListModelsResp {
            models: None,
            count: None,
        }
    }
}

