/*
 * IIoT OpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OriginalReports {
    #[serde(rename = "sync_time", skip_serializing_if = "Option::is_none")]
    pub sync_time: Option<String>,
    #[serde(rename = "aging_time", skip_serializing_if = "Option::is_none")]
    pub aging_time: Option<String>,
}

impl OriginalReports {
    pub fn new() -> OriginalReports {
        OriginalReports {
            sync_time: None,
            aging_time: None,
        }
    }
}

