/*
 * IIoT OpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PropOutputExpression {
    #[serde(rename = "expression")]
    pub expression: String,
    #[serde(rename = "property_path")]
    pub property_path: String,
}

impl PropOutputExpression {
    pub fn new(expression: String, property_path: String) -> PropOutputExpression {
        PropOutputExpression {
            expression,
            property_path,
        }
    }
}

