/*
 * IIoT OpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PropertiesGetReq {
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<String>>,
    #[serde(rename = "components", skip_serializing_if = "Option::is_none")]
    pub components: Option<std::collections::HashMap<String, models::PropertiesGetReq>>,
}

impl PropertiesGetReq {
    pub fn new() -> PropertiesGetReq {
        PropertiesGetReq {
            properties: None,
            components: None,
        }
    }
}

