/*
 * IIoT OpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryViewNodesRsp {
    #[serde(rename = "level_id", skip_serializing_if = "Option::is_none")]
    pub level_id: Option<String>,
    #[serde(rename = "node_id", skip_serializing_if = "Option::is_none")]
    pub node_id: Option<String>,
    #[serde(rename = "node_name", skip_serializing_if = "Option::is_none")]
    pub node_name: Option<String>,
    #[serde(rename = "display_order", skip_serializing_if = "Option::is_none")]
    pub display_order: Option<i32>,
    #[serde(rename = "create_time", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
    #[serde(rename = "catalog_nodes", skip_serializing_if = "Option::is_none")]
    pub catalog_nodes: Option<Vec<models::EnrichedCatalogNode>>,
    #[serde(rename = "thing_nodes", skip_serializing_if = "Option::is_none")]
    pub thing_nodes: Option<Vec<models::EnrichedThingNode>>,
}

impl QueryViewNodesRsp {
    pub fn new() -> QueryViewNodesRsp {
        QueryViewNodesRsp {
            level_id: None,
            node_id: None,
            node_name: None,
            display_order: None,
            create_time: None,
            update_time: None,
            catalog_nodes: None,
            thing_nodes: None,
        }
    }
}

