/*
 * IIoT OpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCatalogsReq {
    #[serde(rename = "catalogs")]
    pub catalogs: Vec<models::CatalogOrder>,
}

impl UpdateCatalogsReq {
    pub fn new(catalogs: Vec<models::CatalogOrder>) -> UpdateCatalogsReq {
        UpdateCatalogsReq {
            catalogs,
        }
    }
}

