/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CatalogNode;
import org.openapitools.client.model.ThingNode;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AddViewNodesReq
 */
public class AddViewNodesReqTest {
    private final AddViewNodesReq model = new AddViewNodesReq();

    /**
     * Model tests for AddViewNodesReq
     */
    @Test
    public void testAddViewNodesReq() {
        // TODO: test AddViewNodesReq
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'catalogNode'
     */
    @Test
    public void catalogNodeTest() {
        // TODO: test catalogNode
    }

    /**
     * Test the property 'thingNodes'
     */
    @Test
    public void thingNodesTest() {
        // TODO: test thingNodes
    }

}
