/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ModifyCatalogNode;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModifyViewNodesReq
 */
public class ModifyViewNodesReqTest {
    private final ModifyViewNodesReq model = new ModifyViewNodesReq();

    /**
     * Model tests for ModifyViewNodesReq
     */
    @Test
    public void testModifyViewNodesReq() {
        // TODO: test ModifyViewNodesReq
    }

    /**
     * Test the property 'catalogNodes'
     */
    @Test
    public void catalogNodesTest() {
        // TODO: test catalogNodes
    }

}
