/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OtstatReports
 */
public class OtstatReportsTest {
    private final OtstatReports model = new OtstatReports();

    /**
     * Model tests for OtstatReports
     */
    @Test
    public void testOtstatReports() {
        // TODO: test OtstatReports
    }

    /**
     * Test the property 'statTime'
     */
    @Test
    public void statTimeTest() {
        // TODO: test statTime
    }

    /**
     * Test the property 'agingTime'
     */
    @Test
    public void agingTimeTest() {
        // TODO: test agingTime
    }

    /**
     * Test the property 'statStatus'
     */
    @Test
    public void statStatusTest() {
        // TODO: test statStatus
    }

    /**
     * Test the property 'statResult'
     */
    @Test
    public void statResultTest() {
        // TODO: test statResult
    }

}
