/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PropOutputExpression
 */
public class PropOutputExpressionTest {
    private final PropOutputExpression model = new PropOutputExpression();

    /**
     * Model tests for PropOutputExpression
     */
    @Test
    public void testPropOutputExpression() {
        // TODO: test PropOutputExpression
    }

    /**
     * Test the property 'expression'
     */
    @Test
    public void expressionTest() {
        // TODO: test expression
    }

    /**
     * Test the property 'propertyPath'
     */
    @Test
    public void propertyPathTest() {
        // TODO: test propertyPath
    }

}
