/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ColumnSchema;
import org.openapitools.client.model.IndexSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TableSchema
 */
public class TableSchemaTest {
    private final TableSchema model = new TableSchema();

    /**
     * Model tests for TableSchema
     */
    @Test
    public void testTableSchema() {
        // TODO: test TableSchema
    }

    /**
     * Test the property 'columns'
     */
    @Test
    public void columnsTest() {
        // TODO: test columns
    }

    /**
     * Test the property 'primaryKey'
     */
    @Test
    public void primaryKeyTest() {
        // TODO: test primaryKey
    }

    /**
     * Test the property 'indexes'
     */
    @Test
    public void indexesTest() {
        // TODO: test indexes
    }

}
