/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ThingDTO
 */
public class ThingDTOTest {
    private final ThingDTO model = new ThingDTO();

    /**
     * Model tests for ThingDTO
     */
    @Test
    public void testThingDTO() {
        // TODO: test ThingDTO
    }

    /**
     * Test the property 'thingId'
     */
    @Test
    public void thingIdTest() {
        // TODO: test thingId
    }

    /**
     * Test the property 'thingName'
     */
    @Test
    public void thingNameTest() {
        // TODO: test thingName
    }

    /**
     * Test the property 'modelId'
     */
    @Test
    public void modelIdTest() {
        // TODO: test modelId
    }

    /**
     * Test the property 'modelName'
     */
    @Test
    public void modelNameTest() {
        // TODO: test modelName
    }

}
