/*
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AgingSettings;
import org.openapitools.client.model.UpdateTableSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateTableRequest
 */
public class UpdateTableRequestTest {
    private final UpdateTableRequest model = new UpdateTableRequest();

    /**
     * Model tests for UpdateTableRequest
     */
    @Test
    public void testUpdateTableRequest() {
        // TODO: test UpdateTableRequest
    }

    /**
     * Test the property 'tableName'
     */
    @Test
    public void tableNameTest() {
        // TODO: test tableName
    }

    /**
     * Test the property 'catalogId'
     */
    @Test
    public void catalogIdTest() {
        // TODO: test catalogId
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'tableSchema'
     */
    @Test
    public void tableSchemaTest() {
        // TODO: test tableSchema
    }

    /**
     * Test the property 'agingSettings'
     */
    @Test
    public void agingSettingsTest() {
        // TODO: test agingSettings
    }

}
