/* tslint:disable */
/* eslint-disable */
/**
 * IIoT OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTableRequest,
  TableInfo,
} from '../models/index';
import {
    CreateTableRequestFromJSON,
    CreateTableRequestToJSON,
    TableInfoFromJSON,
    TableInfoToJSON,
} from '../models/index';

export interface CreateTableOperationRequest {
    xAuthToken: string;
    projectId: string;
    createTableRequest: CreateTableRequest;
}

/**
 * 
 */
export class TableApi extends runtime.BaseAPI {

    /**
     * 创建表
     */
    async createTableRaw(requestParameters: CreateTableOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TableInfo>> {
        if (requestParameters['xAuthToken'] == null) {
            throw new runtime.RequiredError(
                'xAuthToken',
                'Required parameter "xAuthToken" was null or undefined when calling createTable().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createTable().'
            );
        }

        if (requestParameters['createTableRequest'] == null) {
            throw new runtime.RequiredError(
                'createTableRequest',
                'Required parameter "createTableRequest" was null or undefined when calling createTable().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xAuthToken'] != null) {
            headerParameters['X-Auth-Token'] = String(requestParameters['xAuthToken']);
        }

        const response = await this.request({
            path: `/v5/{project_id}/tables`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTableRequestToJSON(requestParameters['createTableRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TableInfoFromJSON(jsonValue));
    }

    /**
     * 创建表
     */
    async createTable(requestParameters: CreateTableOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TableInfo> {
        const response = await this.createTableRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
